#!/usr/bin/env node

"use strict"
const fs = require('fs')

function usage() {
    console.log(`usage: ${process.argv[1]} [fromDate [toDate]]

List information about prior Mythril Platform analyses

Set environment variables EMAIL and MYTHRIL_API_KEY before using.
`)
    process.exit(1)
}

require('./helper')

const argLen = process.argv.length
if (argLen === 3 &&
    process.argv[2].match(/^[-]{0,2}h(?:elp)?$/)) {
    usage()
}

let queryString = ''
if (argLen === 3) {
    if (process.argv[2].match(/^[-]{0,2}h(?:elp)?$/)) {
	usage()
    } else {
	queryString = `dateFrom=${process.argv[2]}`
    }
}

/**********************************
  Example code starts here ...
***********************************/

const options = {
    apiKey: process.env.MYTHRIL_API_KEY,
    userEmail: process.env.EMAIL,
    platforms: []  // client chargeback
}

const armlet = require('../index') // if not installed
// const armlet = require('armlet') // if installed

const client = new armlet.Client(options)

client.listAnalyses(queryString)
    .then(issues => {
        console.log(issues)
    }).catch(err => {
        console.log(err)
    })
